name: okcolor
description: "A Dart package for working with colors in the Oklab color space,
  providing utilities for color manipulation, conversion, and analysis."
version: 1.0.0
homepage: null

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
